# Generated by Django 4.2.7 on 2025-10-28 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EbayItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100, unique=True)),
                ('title', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('listing_type', models.CharField(blank=True, max_length=100, null=True)),
                ('condition', models.CharField(blank=True, max_length=200, null=True)),
                ('seller_username', models.CharField(blank=True, max_length=500, null=True)),
                ('view_item_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_availability_status', models.CharField(blank=True, max_length=50, null=True)),
                ('estimated_available_quantity', models.IntegerField(blank=True, null=True)),
                ('estimated_sold_quantity', models.IntegerField(blank=True, null=True)),
                ('estimated_remaining_quantity', models.IntegerField(blank=True, null=True)),
                ('buying_options', models.JSONField(blank=True, null=True)),
                ('shipping_options', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'eBay Item',
                'verbose_name_plural': 'eBay Items',
                'db_table': 'ebay_items',
            },
        ),
        migrations.CreateModel(
            name='EbaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_refresh_enabled', models.BooleanField(default=True)),
                ('dashboard_refresh_interval', models.IntegerField(default=30)),
                ('auto_sync_enabled', models.BooleanField(default=True)),
                ('sync_interval', models.IntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'eBay Setting',
                'verbose_name_plural': 'eBay Settings',
                'db_table': 'ebay_settings',
            },
        ),
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('create', 'Create Listing'), ('update', 'Update Listing')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped - Manual Override')], default='pending', max_length=20)),
                ('inventory_item_id', models.CharField(max_length=100)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sync_data', models.JSONField(default=dict)),
                ('result_data', models.JSONField(default=dict)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('ebay_settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ebay_integration.ebaysettings')),
            ],
            options={
                'verbose_name': 'Sync Operation',
                'verbose_name_plural': 'Sync Operations',
                'db_table': 'sync_operations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='sync_operat_status_7e49b6_idx'), models.Index(fields=['inventory_item_id'], name='sync_operat_invento_530635_idx'), models.Index(fields=['sku'], name='sync_operat_sku_20deca_idx')],
            },
        ),
    ]
