# Generated by Django 4.2.7 on 2025-11-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_integration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SyncOperation',
        ),
    ]
