# Generated by Django 4.2.7 on 2025-11-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_integration', '0002_delete_syncoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaysettings',
            name='last_sync_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
