# Generated by Django 4.2.7 on 2025-08-22 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Barcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                ("format", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("additional_info", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Coin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cert_number", models.CharField(max_length=100, unique=True)),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "display_grade",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("grade_type", models.CharField(blank=True, max_length=100, null=True)),
                ("encapsulation_date", models.DateField(blank=True, null=True)),
                ("graded_date", models.DateField(blank=True, null=True)),
                (
                    "submission_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("grader_notes", models.JSONField(blank=True, default=list, null=True)),
                ("pedigree", models.CharField(blank=True, max_length=255, null=True)),
                ("pedigree2", models.CharField(blank=True, max_length=255, null=True)),
                ("grade_comment", models.TextField(blank=True, null=True)),
                (
                    "collectible_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "rollup_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "denomination",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("year", models.CharField(blank=True, max_length=10, null=True)),
                ("proof_mint", models.CharField(blank=True, max_length=100, null=True)),
                ("mint_mark", models.CharField(blank=True, max_length=10, null=True)),
                ("strike", models.CharField(blank=True, max_length=100, null=True)),
                ("variety1", models.CharField(blank=True, max_length=500, null=True)),
                ("variety2", models.CharField(blank=True, max_length=100, null=True)),
                ("variety3", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "universal_coin_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fineness", models.CharField(blank=True, max_length=50, null=True)),
                ("metal_type", models.CharField(blank=True, max_length=50, null=True)),
                ("weight_grams", models.FloatField(blank=True, null=True)),
                ("weight_ounces", models.FloatField(blank=True, null=True)),
                ("front_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "front_thumbnail_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("rear_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "rear_thumbnail_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "holder_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fetched_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-fetched_at"],
            },
        ),
    ]
