# Generated by Django 4.2.7 on 2025-11-17 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        """
                        DO $$
                        BEGIN
                            IF to_regclass('public.clients') IS NULL AND to_regclass('public.inventory_client') IS NOT NULL THEN
                                ALTER TABLE public.inventory_client RENAME TO clients;
                            END IF;
                        END
                        $$;
                        """
                    ),
                    reverse_sql=(
                        """
                        DO $$
                        BEGIN
                            IF to_regclass('public.inventory_client') IS NULL AND to_regclass('public.clients') IS NOT NULL THEN
                                ALTER TABLE public.clients RENAME TO inventory_client;
                            END IF;
                        END
                        $$;
                        """
                    ),
                )
            ],
            state_operations=[
                migrations.AlterModelTable(
                    name='client',
                    table='clients',
                )
            ],
        ),
    ]
