# Generated by Django 4.2.7 on 2025-08-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="inventoryitem",
            name="inventory_i_status_fbf4f8_idx",
        ),
        migrations.RemoveIndex(
            model_name="inventoryitem",
            name="inventory_i_categor_bebcf8_idx",
        ),
        migrations.RemoveIndex(
            model_name="inventoryitem",
            name="inventory_i_date_ad_c94761_idx",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="client_id",
            new_name="client",
        ),
        migrations.RenameField(
            model_name="inventoryitem",
            old_name="client_id",
            new_name="client",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="client_id",
            new_name="client",
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name", "client")},
        ),
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("name", "parent", "client")},
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["status", "client"], name="inventory_i_status_8da9c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["category", "client"], name="inventory_i_categor_3e627a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["date_added", "client"], name="inventory_i_date_ad_df7e2b_idx"
            ),
        ),
    ]
