# Generated by Django 4.2.7 on 2025-08-07 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory",
            "0002_remove_inventoryitem_inventory_i_status_fbf4f8_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="capacity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="path",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="location",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="inventory.location",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="type",
            field=models.CharField(
                choices=[
                    ("site", "Site"),
                    ("room", "Room"),
                    ("shelf", "Shelf"),
                    ("box", "Box"),
                    ("row", "Row"),
                    ("slot", "Slot"),
                ],
                max_length=20,
            ),
        ),
    ]
