# Generated by Django 4.2.7 on 2025-08-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_location_capacity_location_path_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="inventoryitem",
            name="inventory_i_date_ad_df7e2b_idx",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="created_at",
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="identification_number",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="lookup_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["identification_number", "client"],
                name="inventory_i_identif_e4db8c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("identification_number", ""), _negated=True),
                fields=("client", "identification_number"),
                name="uniq_client_identification_number_per_client",
            ),
        ),
    ]
