# Generated by Django 4.2.7 on 2025-09-16 13:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory",
            "0004_remove_inventoryitem_inventory_i_date_ad_df7e2b_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="created_by",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="updated_by",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
    ]
