# Generated by Django 4.2.7 on 2025-10-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryitem_created_by_inventoryitem_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='is_listed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
