# Generated by Django 4.2.7 on 2025-11-18 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0002_alter_client_table'),
        ('inventory', '0006_inventoryitem_is_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.client'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.client'),
        ),
        migrations.AlterField(
            model_name='location',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.client'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
