# Generated by Django 4.2.7 on 2026-01-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_ivfflat_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqsqlcache',
            name='usebar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faqsqlcache',
            name='usepie',
            field=models.BooleanField(default=False),
        ),
    ]
