# Generated by Django 4.2.7 on 2025-11-17 12:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('module_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'Modules',
            },
        ),
        # migrations.CreateModel(
        #     name='Role',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100, unique=True)),
        #         ('description', models.TextField(blank=True, null=True)),
        #         ('color', models.CharField(default='#6B7280', max_length=20)),
        #         ('is_custom', models.BooleanField(default=True)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #     ],
        # ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_uid', models.CharField(blank=True, max_length=128, null=True)),
                ('created_by_email', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by_uid', models.CharField(blank=True, max_length=128, null=True)),
                ('updated_by_email', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'db_table': 'UserRoles',
            },
        ),
        # migrations.CreateModel(
        #     name='Permission',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        #         ('module', models.IntegerField(choices=[(1, 'Inventory'), (2, 'Locations'), (3, 'Ebay'), (4, 'Reports'), (5, 'Users'), (6, 'Roles'), (7, 'Settings')])),
        #         ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('admin', 'Admin')], max_length=50)),
        #         ('granted', models.BooleanField(default=False)),
        #         ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='common.role')),
        #     ],
        #     options={
        #         'unique_together': {('role', 'module', 'action')},
        #     },
        # ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='common.module')),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='common.userroles')),
            ],
            options={
                'verbose_name': 'Module Permission',
                'verbose_name_plural': 'Module Permissions',
                'db_table': 'ModulePermissions',
                'unique_together': {('user_role', 'module')},
            },
        ),
    ]
