# Generated by Django 4.2.7 on 2025-11-25 17:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#6B7280', max_length=20)),
                ('is_custom', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='modulepermission',
            name='module_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.IntegerField(choices=[(1, 'inventory'), (2, 'locations'), (3, 'ebay'), (4, 'reports'), (5, 'users'), (6, 'roles'), (7, 'settings')])),
                ('action', models.CharField(choices=[('view', 'view'), ('create', 'create'), ('edit', 'edit'), ('delete', 'delete'), ('admin', 'admin')], max_length=50)),
                ('granted', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='common.role')),
            ],
            options={
                'unique_together': {('role', 'module', 'action')},
            },
        ),
    ]
